cache:
 - C:\projects\sources

install:
 - set SOURCES="C:\projects\sources"
 - if not exist "%SOURCES%" mkdir "%SOURCES%"
 - del "%SOURCES%\*.msi"

 # download
 - set PERL530PACKAGE=strawberry-perl-5.30.2.1-64bit-portable.zip
 - if not exist "%SOURCES%\%PERL530PACKAGE%" curl -fsS -o "%SOURCES%\%PERL530PACKAGE%" http://strawberryperl.com/download/5.30.2.1/%PERL530PACKAGE%
 - set PERL530=C:\projects\perl530

 - 7z x "%SOURCES%\%PERL530PACKAGE%" -o"%PERL530%"

 - set OLDPATH=%PATH%
 - set PATH=%PERL530%\perl\bin;%PERL530%\perl\site\bin;%PERL530%\c\bin;%OLDPATH%
 - cd C:\projects\p5-ZMQ-Raw
 - cpanm --quiet --notest Dist::Zilla Dist::Zilla::PluginBundle::Author::ALEXBIO App::Ack
 - dzil authordeps --missing | ack -v "inc::" | cpanm --notest --quiet
 - dzil listdeps --missing | cpanm --notest --quiet
 - dzil build --in ZMQ-Raw-530

build_script:
 - set PATH=%PERL530%\perl\bin;%PERL530%\perl\site\bin;%PERL530%\c\bin;%OLDPATH%
 - cd C:\projects\p5-ZMQ-Raw\ZMQ-Raw-530
 - perl -V
 - perl Makefile.PL
 - gmake test
